import Link from "next/link";
import { ArrowRight, Check, FileText, Layers3, Sparkles, Zap } from "lucide-react";
const features = [{ icon: Zap, title: "Veloce, davvero", text: "Editor guidato e anteprima istantanea: dal foglio bianco a un CV pronto in pochi minuti." }, { icon: Layers3, title: "Sempre flessibile", text: "Riordina sezioni, cambia template e crea una versione per ogni candidatura." }, { icon: FileText, title: "PDF ATS-friendly", text: "Layout professionali, testo selezionabile ed esportazione A4 ottimizzata." }];
export default function Home() { return <main className="overflow-hidden">
  <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Link href="/" className="flex items-center gap-2 text-lg font-bold"><span className="grid size-8 place-items-center rounded-lg bg-ink text-white">V</span> Vitae</Link><div className="flex items-center gap-2"><Link href="/login" className="px-4 py-2 text-sm font-semibold">Accedi</Link><Link href="/register" className="rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white">Crea il tuo CV</Link></div></nav>
  <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-2 lg:py-28"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-sage-100 bg-sage-50 px-3 py-1.5 text-xs font-semibold text-sage-700"><Sparkles size={14}/> Il modo più semplice di raccontare il tuo valore</div><h1 className="max-w-3xl font-display text-5xl font-medium leading-[1.04] tracking-tight sm:text-6xl lg:text-7xl">Il tuo curriculum professionale, <em className="text-sage-600">pronto in pochi minuti.</em></h1><p className="mt-6 max-w-xl text-lg leading-8 text-gray-600">Compila, personalizza e scarica. Vitae ti guida passo dopo passo e mostra ogni modifica in tempo reale.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-xl bg-ink px-6 py-3.5 font-semibold text-white">Crea il tuo CV <ArrowRight size={18}/></Link><a href="#come-funziona" className="rounded-xl border border-gray-200 bg-white px-6 py-3.5 font-semibold">Scopri come funziona</a></div><p className="mt-4 flex items-center gap-2 text-sm text-gray-500"><Check size={15} className="text-sage-600"/> Nessuna carta richiesta · Inizia gratis</p></div>
  <div className="relative"><div className="absolute -inset-12 -z-10 rounded-full bg-sage-100/50 blur-3xl"/><div className="rounded-3xl border border-gray-200 bg-white p-3 shadow-soft"><div className="flex items-center gap-2 border-b px-3 py-2 text-xs text-gray-400"><i className="size-2 rounded-full bg-red-300"/><i className="size-2 rounded-full bg-amber-300"/><i className="size-2 rounded-full bg-green-300"/><span className="ml-2">Il mio curriculum</span></div><div className="grid grid-cols-[.75fr_1.25fr] gap-3 bg-gray-50 p-3"><div className="space-y-3 rounded-xl bg-white p-4"><div className="h-3 w-2/3 rounded bg-gray-200"/><div className="h-9 rounded-lg border"/><div className="h-9 rounded-lg border"/><div className="h-20 rounded-lg border"/><div className="h-9 w-1/2 rounded-lg bg-ink"/></div><div className="aspect-[.707] rounded-sm bg-white p-8 shadow"><div className="h-4 w-2/3 bg-sage-600"/><div className="mt-2 h-2 w-1/3 bg-gray-200"/><div className="mt-8 h-2 w-1/4 bg-gray-700"/><div className="mt-3 space-y-2"><div className="h-1.5 bg-gray-100"/><div className="h-1.5 bg-gray-100"/><div className="h-1.5 w-4/5 bg-gray-100"/></div></div></div></div></div></section>
  <section id="come-funziona" className="border-y bg-white py-24"><div className="mx-auto max-w-7xl px-6"><p className="text-sm font-bold uppercase tracking-widest text-sage-600">Come funziona</p><h2 className="mt-3 font-display text-4xl">Tre passi. Un&apos;ottima prima impressione.</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{["Inserisci i tuoi dati", "Scegli il tuo stile", "Scarica e candidati"].map((x,i)=><div key={x} className="rounded-2xl border p-6"><span className="font-display text-4xl text-sage-500">0{i+1}</span><h3 className="mt-8 text-lg font-bold">{x}</h3><p className="mt-2 text-sm leading-6 text-gray-500">{i===0?"Segui i suggerimenti dell'editor, senza preoccuparti del layout.":i===1?"Prova i template Classic, Modern e Minimal senza perdere alcun dato.":"Esporta un PDF A4 nitido, pronto per recruiter e sistemi ATS."}</p></div>)}</div></div></section>
  <section id="template" className="mx-auto max-w-7xl px-6 py-24"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-sage-600">Template disponibili</p><h2 className="mt-3 font-display text-4xl">Il tuo percorso, presentato al meglio.</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{["Classic","Modern","Minimal"].map((x,i)=><div key={x}><div className={`aspect-[.707] rounded-2xl border p-8 ${i===1?"bg-ink text-white":"bg-white"}`}><div className="h-5 w-2/3 rounded bg-sage-500"/><div className="mt-2 h-2 w-1/3 rounded bg-gray-300"/><div className="mt-10 space-y-3">{[1,2,3,4].map(n=><div key={n} className={`h-2 rounded ${i===1?"bg-white/20":"bg-gray-100"}`}/>)}</div></div><h3 className="mt-4 font-bold">{x}</h3><p className="text-sm text-gray-500">ATS-friendly · A4 · Multipagina</p></div>)}</div></section>
  <section className="bg-sage-50 py-24"><div className="mx-auto max-w-7xl px-6"><div className="grid gap-6 md:grid-cols-3">{features.map(({icon:Icon,title,text})=><div key={title} className="rounded-2xl bg-white p-7"><Icon className="text-sage-600"/><h3 className="mt-6 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-500">{text}</p></div>)}</div></div></section>
  <section id="faq" className="mx-auto max-w-3xl px-6 py-24"><h2 className="text-center font-display text-4xl">Domande frequenti</h2><div className="mt-10 divide-y">{[["Posso creare più curriculum?","Sì. Puoi creare, duplicare e personalizzare una versione per ogni candidatura."],["Il PDF è compatibile con gli ATS?","Sì. I template usano una struttura semantica semplice e testo realmente selezionabile."],["I miei dati sono al sicuro?","Ogni curriculum è isolato per utente e ogni operazione viene autorizzata sul server."]].map(([q,a])=><details key={q} className="group py-5"><summary className="cursor-pointer list-none font-semibold">{q}<span className="float-right">+</span></summary><p className="pt-3 text-sm leading-6 text-gray-500">{a}</p></details>)}</div></section>
  <section className="mx-4 mb-4 rounded-3xl bg-ink px-6 py-20 text-center text-white"><h2 className="font-display text-4xl sm:text-5xl">Il prossimo passo inizia da qui.</h2><p className="mx-auto mt-4 max-w-lg text-white/60">Crea oggi un curriculum chiaro, professionale e davvero tuo.</p><Link href="/register" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 font-semibold text-ink">Crea il tuo CV <ArrowRight size={18}/></Link></section>
  <footer className="mx-auto flex max-w-7xl justify-between px-6 py-8 text-sm text-gray-500"><span>© 2026 Vitae</span><span>Fatto con cura in Italia.</span></footer>
  </main> }
