"use client";
import { ChevronDown, Plus, Trash2 } from "lucide-react"; import type { ResumeDocument, Experience, Education, Language, Project, Certification, CustomLink } from "@/types/resume"; import { uid } from "@/lib/utils"; import { SectionList } from "./section-list";
type Props={resume:ResumeDocument;update:(fn:(r:ResumeDocument)=>ResumeDocument)=>void};
export function ResumeEditor({resume,update}:Props){const c=resume.content;const setPersonal=(k:keyof typeof c.personal,v:string)=>update(r=>({...r,content:{...r.content,personal:{...r.content.personal,[k]:v}}}));const content=(patch:Partial<typeof c>)=>update(r=>({...r,content:{...r.content,...patch}}));return <div className="space-y-3 pb-24">
<Panel title="Informazioni personali" open><div className="grid grid-cols-2 gap-3"><Input label="Nome" value={c.personal.firstName} onChange={v=>setPersonal("firstName",v)} placeholder="Giulia"/><Input label="Cognome" value={c.personal.lastName} onChange={v=>setPersonal("lastName",v)} placeholder="Bianchi"/><div className="col-span-2"><Input label="Titolo professionale" value={c.personal.jobTitle} onChange={v=>setPersonal("jobTitle",v)} placeholder="Product Designer"/></div><Input label="Email" value={c.personal.email} onChange={v=>setPersonal("email",v)} placeholder="nome@email.it"/><Input label="Telefono" value={c.personal.phone} onChange={v=>setPersonal("phone",v)} placeholder="+39 333..."/><Input label="Città" value={c.personal.city} onChange={v=>setPersonal("city",v)} placeholder="Milano"/><Input label="Paese" value={c.personal.country} onChange={v=>setPersonal("country",v)} placeholder="Italia"/><Input label="LinkedIn" value={c.personal.linkedin} onChange={v=>setPersonal("linkedin",v)} placeholder="linkedin.com/in/..."/><Input label="Portfolio" value={c.personal.website} onChange={v=>setPersonal("website",v)} placeholder="iltuosito.it"/></div></Panel>
<Panel title="Profilo professionale"><Area label="Presentati in 3–5 righe" value={c.profile} onChange={v=>content({profile:v})} placeholder="Racconta il tuo valore, la tua esperienza e ciò che cerchi..."/></Panel>
<Collection title="Esperienza lavorativa" items={c.experience} addLabel="Aggiungi esperienza" onAdd={()=>content({experience:[...c.experience,{id:uid(),company:"",role:"",city:"",startDate:"",endDate:"",current:false,description:""}]})} onDelete={id=>content({experience:c.experience.filter(x=>x.id!==id)})}>{(x:Experience)=><div className="grid grid-cols-2 gap-3"><Input label="Ruolo" value={x.role} onChange={v=>content({experience:replace(c.experience,x.id,{role:v})})} placeholder="Product Designer"/><Input label="Azienda" value={x.company} onChange={v=>content({experience:replace(c.experience,x.id,{company:v})})} placeholder="Azienda Srl"/><Input label="Data inizio" value={x.startDate} onChange={v=>content({experience:replace(c.experience,x.id,{startDate:v})})} type="month"/><Input label="Data fine" value={x.endDate} onChange={v=>content({experience:replace(c.experience,x.id,{endDate:v})})} type="month"/><label className="col-span-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={x.current} onChange={e=>content({experience:replace(c.experience,x.id,{current:e.target.checked})})}/> Attualmente lavoro qui</label><div className="col-span-2"><Area label="Risultati e responsabilità" value={x.description} onChange={v=>content({experience:replace(c.experience,x.id,{description:v})})} placeholder="Descrivi risultati concreti e usa dati quando possibile..."/></div></div>}</Collection>
<Collection title="Formazione" items={c.education} addLabel="Aggiungi formazione" onAdd={()=>content({education:[...c.education,{id:uid(),school:"",degree:"",field:"",city:"",startDate:"",endDate:"",description:""}]})} onDelete={id=>content({education:c.education.filter(x=>x.id!==id)})}>{(x:Education)=><div className="grid grid-cols-2 gap-3"><Input label="Scuola / Università" value={x.school} onChange={v=>content({education:replace(c.education,x.id,{school:v})})}/><Input label="Titolo di studio" value={x.degree} onChange={v=>content({education:replace(c.education,x.id,{degree:v})})}/><Input label="Campo di studi" value={x.field} onChange={v=>content({education:replace(c.education,x.id,{field:v})})}/><Input label="Città" value={x.city} onChange={v=>content({education:replace(c.education,x.id,{city:v})})}/><Input label="Data inizio" value={x.startDate} onChange={v=>content({education:replace(c.education,x.id,{startDate:v})})}/><Input label="Data fine" value={x.endDate} onChange={v=>content({education:replace(c.education,x.id,{endDate:v})})}/></div>}</Collection>
<Panel title="Competenze"><Tags values={c.skills} onChange={skills=>content({skills})}/></Panel>
<SimpleCollection title="Lingue" items={c.languages} blank={{id:"",name:"",level:""}} add="Aggiungi lingua" fields={[["name","Lingua"],["level","Livello"]]} set={languages=>content({languages:languages as Language[]})}/>
<SimpleCollection title="Progetti" items={c.projects} blank={{id:"",name:"",description:"",technologies:"",link:""}} add="Aggiungi progetto" fields={[["name","Nome progetto"],["technologies","Tecnologie"],["description","Descrizione"],["link","Link"]]} set={projects=>content({projects:projects as Project[]})}/>
<SimpleCollection title="Certificazioni" items={c.certifications} blank={{id:"",name:"",issuer:"",date:"",link:""}} add="Aggiungi certificazione" fields={[["name","Nome"],["issuer","Ente"],["date","Data"],["link","Link"]]} set={certifications=>content({certifications:certifications as Certification[]})}/>
<SimpleCollection title="Link aggiuntivi" items={c.links} blank={{id:"",label:"",url:""}} add="Aggiungi link" fields={[["label","Etichetta"],["url","URL"]]} set={links=>content({links:links as CustomLink[]})}/>
<Panel title="Ordine e visibilità"><p className="mb-3 text-xs leading-5 text-gray-500">Trascina le sezioni per riordinarle. Nascondile senza eliminare i dati.</p><SectionList order={c.sectionOrder} hidden={c.hiddenSections} onOrder={sectionOrder=>content({sectionOrder})} onToggle={id=>content({hiddenSections:c.hiddenSections.includes(id)?c.hiddenSections.filter(x=>x!==id):[...c.hiddenSections,id]})}/></Panel></div>}
function Panel({title,children,open=false}:{title:string;children:React.ReactNode;open?:boolean}){return <details open={open} className="group rounded-2xl border bg-white"><summary className="flex cursor-pointer list-none items-center justify-between p-5 font-semibold">{title}<ChevronDown size={17} className="transition group-open:rotate-180"/></summary><div className="border-t p-5">{children}</div></details>}
function Collection<T extends{id:string}>({title,items,onAdd,onDelete,addLabel,children}:{title:string;items:T[];onAdd:()=>void;onDelete:(id:string)=>void;addLabel:string;children:(x:T)=>React.ReactNode}){return <Panel title={title}><div className="space-y-3">{items.map((x,i)=><details open={i===items.length-1} key={x.id} className="rounded-xl border"><summary className="flex cursor-pointer list-none items-center p-3 text-sm font-semibold"><span className="flex-1">{("role" in x&&String(x.role))||("degree" in x&&String(x.degree))||`${title} ${i+1}`}</span><button onClick={e=>{e.preventDefault();onDelete(x.id)}} className="text-gray-400 hover:text-red-600"><Trash2 size={15}/></button></summary><div className="border-t p-4">{children(x)}</div></details>)}<button onClick={onAdd} className="flex items-center gap-2 text-sm font-semibold text-sage-700"><Plus size={16}/>{addLabel}</button></div></Panel>}
function SimpleCollection<T extends{id:string}>({title,items,blank,add,fields,set}:{title:string;items:T[];blank:T;add:string;fields:string[][];set:(x:T[])=>void}){return <Collection title={title} items={items} addLabel={add} onAdd={()=>set([...items,{...blank,id:uid()}])} onDelete={id=>set(items.filter(x=>x.id!==id))}>{x=><div className="grid grid-cols-2 gap-3">{fields.map(([key,label])=><Input key={key} label={label} value={String(x[key as keyof T]??"")} onChange={v=>set(replace(items,x.id,{[key]:v}) as T[])}/>)}</div>}</Collection>}
function Input({label,value,onChange,placeholder,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label className="block text-xs font-semibold text-gray-600">{label}<input className="input" type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Area({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="block text-xs font-semibold text-gray-600">{label}<textarea className="input" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Tags({values,onChange}:{values:string[];onChange:(x:string[])=>void}){return <div><div className="flex flex-wrap gap-2">{values.map((x,i)=><button key={`${x}-${i}`} onClick={()=>onChange(values.filter((_,n)=>n!==i))} className="rounded-lg bg-sage-50 px-2.5 py-1.5 text-xs font-semibold text-sage-700">{x} ×</button>)}</div><input className="input mt-3" placeholder="Scrivi una competenza e premi Invio" onKeyDown={e=>{if(e.key==="Enter"&&e.currentTarget.value.trim()){e.preventDefault();onChange([...values,e.currentTarget.value.trim()]);e.currentTarget.value=""}}}/></div>}
function replace<T extends{id:string}>(items:T[],id:string,patch:Partial<T>){return items.map(x=>x.id===id?{...x,...patch}:x)}
